### ISSUE TITLE
HRDetect test example problem (small issue)

### ISSUE THREAD

**Issue by AndreVidas** [Nik-Zainal-Group/signature.tools.lib#1]
Hi Nik-Zainal et al.

I'm currently running through the test example here on GitHub, but it seems that the cosmic30 variable is not defined, so I just wanted to point that out for improvement. I guess that you're using the data/COSMIC30_subs_signatures.txt to define the cosmic30 variable? If not, please let me know what you're using.

Best regards,
André

**Comment by andreadega** [comment]
Hi Andre,

Thanks for pointing that out, the variable should be:

```
signature.tools.lib::COSMIC30_subs_signatures
```

See if that works, I will update the example.
Andrea

**Comment by ahwanpandey** [comment]
Just FYI, I still had to use `signature.tools.lib::cosmic30` ; and I just downloaded the master from git.

**Comment by ahwanpandey** [comment]
nevermind, `signature.tools.lib::COSMIC30_subs_signatures` is working all of a sudden.
