### ISSUE TITLE
Obtaining the percentage of mutations associated with each signature 

### ISSUE THREAD

**Issue by beginner984** [Nik-Zainal-Group/signature.tools.lib#10]
I guess by fitting my mutational catalogues against organ specific cancer signatures I am getting the overall mutational burden per sample as below (I am not quite sure)

```
Organ-specific cancer signature | Contribution

Esophagus_A | 4267.41
Esophagus_B | 4996.407
Esophagus_C | 2565.249
Esophagus_D | 4855.811
Esophagus_E | 4164.84
Esophagus_F | 2374.619
Esophagus_G | 1820.741
Esophagus_H | 0


```

How can I obtain `the percentage of mutations associated with each signature rather than absolute numbers`

Because if I am not wrong, the number of mutations assigned to each signature will depend on the overall mutational burden in the sample

Thank you for giving any information

**Comment by andreadega** [comment]
You can simply divide these number by the total number of mutations. You will see that a certain percentage will be missing, that is the *unassigned* proportion, which if large may indicate high uncertainty of signature fit.
