### ISSUE TITLE
Tissue-specific Signatures Example for User Guide

### ISSUE THREAD

**Issue by DarioS** [Nik-Zainal-Group/signature.tools.lib#12]
Example 01 shows how to fit a mutation catalogue to the COSMIC 30 reference signatures. Could an example be added of fitting using one of the PCAWG tissue-specific signatures and back-transforming it into the biologically-annotated COSMIC signatures?

**Comment by andreadega** [comment]
This is indeed something I would like to do, and I hope to find some time to add more examples of usage.

**Comment by andreadega** [comment]
Example 02 shows how to use organ-specific signatutes. So issue closed.
