### ISSUE TITLE
Can I still use my data for your software

### ISSUE THREAD

**Issue by beginner984** [Nik-Zainal-Group/signature.tools.lib#13]
Hello

I receive my data from OCCAMS and I don't have control over data type I therefore don't have `bedpe` format of `SV` instead I have something like this (annotated bedpe)

https://www.dropbox.com/s/h0b4djzirq53e75/LP6008460-DNA_D01_vs_LP6008340-DNA_E02__pv.1.7__rg.grch37_g1k__al.bwa_mem__.manta.filtered.germline.blood.tissue.chroms.passed.bedpe.reheadered.SVannotated.txt?dl=0

For copy number I also have caveman format from SCAT like this

https://www.dropbox.com/s/g4ye072hxl03s29/LP2000325-DNA_A01_vs_LP2000317-DNA_A01.copynumber.caveman.csv?dl=0

I have found your software very comprehensive especially I am very interested in calculating HRD scores 

My question pleases: Is it still possible to use your software on my SV and coy number

Because I don't have allele specific counts for normal sample and original `bedpe`

Thank you very much for any information

**Comment by andreadega** [comment]
Sorry for the late reply. I am not able to access the links you provided.

In any case, you can read the documentation in R (for example type ```?HRDetect_pipeline```) where you will find a detailed description of how to format input files and what is required.

Hope this helps.

**Comment by beginner984** [comment]
Thank you 

I have updated the links

This is one full `annotated SV` (`annotated bedpe`)

https://www.dropbox.com/s/0rwx1yv7h320ipg/LP6005935-DNA_G02_vs_LP6005979-DNA_C01__pv.1.6__rg.grch37_g1k__al.bwa_mem__.manta.filtered.germline.blood.tissue.chroms.passed.bedpe.reheadered.SVannotated.txt?dl=0

And this is caveman copy number I have for same patient 

https://www.dropbox.com/s/woac7vgs0c600f8/LP6008460-DNA_D01_vs_LP6008340-DNA_E02__pv.1.7__rg.grch37_g1k__al.bwa_mem__.copynumber.caveman.csv?dl=0

I looked at required sample inputs 

I am wondering still I can use what I have to run the algorithm and/or I need some input adjustment

Thank you for any help

**Comment by andreadega** [comment]
I think it should be possible, can you send me a private email on this? You can find how to contact me on my profile.

**Comment by andreadega** [comment]
Just to be clearer,

You cannot use these files directly, but you can easily reformat them and use them.

Check ```?HRDetect_pipeline``` to see how. Mostly you will have to rename some columns and make the CSV a tab separate file, and maybe construct some new columns based on what you arleady have.
