### ISSUE TITLE
Dependency 'NNLM' is not available

### ISSUE THREAD

**Issue by pdiakumis** [Nik-Zainal-Group/signature.tools.lib#15]
Hi @andreadega 
I'm trying to install your R package with `devtools::install()`, which gives the following error:

```
ERROR: dependency ‘NNLM’ is not available for package ‘signature.tools.lib’
```

```
> devtools::session_info()
─ Session info ───────────────────────────────────────────────────────────────
 setting  value
 version  R version 3.6.3 (2020-02-29)
 os       macOS Mojave 10.14.6
 system   x86_64, darwin15.6.0
```

I can see that NNLM no longer exists on CRAN (https://cran.r-project.org/web/packages/NNLM/index.html).
Is this package necessary for `signature.tools.lib` to work? 

Kind Regards,
Peter

**Comment by andreadega** [comment]
Hi Peter,

NNLM is a great package, as it provides so many features and flexibility to run NMF. It is not strictly necessary depending on the function you use, but I recommend to install it.

Unfortunately, there seems to be some issue with CRAN, and NNLM is sometimes available and sometimes not.

However, from the link you posted, CRAN redirects you to an archive, where you can download the latest archived version and install it manually. I know it is a bit of a pain, but this is the current way to deal with this issue until we find a better solution.

You can also install it from the github repository:

https://github.com/linxihui/NNLM

**Comment by pdiakumis** [comment]
Thanks Andrea,

Yeah, I tried installing NNLM from GitHub but ran into Rcpp issues (which I suspect is the reason the package might not have made it onto CRAN with the updated R version), so I thought I'd just ask if it is absolutely necessary.
I get the same issues trying to install the older release of NNLM from CRAN.
Anyway, it might be something to do with the Rcpp installation on my local mac since I can install NNLM via Docker with R 3.6.3.

All the best,
Peter

**Comment by pdiakumis** [comment]
Just FYI, in case anyone stumbles on this, updating to the latest version of R 4.0.0 seems to have solved my issue.
