### ISSUE TITLE
Guidance for function SignatureExtraction and the plot interpretation

### ISSUE THREAD

**Issue by Huan-Wang-S4** [Nik-Zainal-Group/signature.tools.lib#17]
Dear team

I have a cohort of ~250 WES HCC cancer samples, with a total of ~ 40K variants in exome region only. My first step is to perform de novo mutational signature extraction to see if I can find any novel signatures to my cohort, and then add that to the COSMIC HCC specific signatures, and then do signature fitting. Previously I was using MutationalPatterns for de novo signature extraction, and now after reading this paper (https://www.nature.com/articles/s43018-020-0027-5) I'm very interested to see if `signature.tools.lib` is better at de novo signature extraction. So my questions are mainly two parts

**First, given the sample size of my WES dataset, how would you suggest to set the parameters for using function `SignatureExtraction`?** 

For example, for the usage below, should I increase the nrepeats (to 100?) and nboots (to 100?) to get a more robust answer? And what would you suggest for `nsig`?  From 2 to 10?

```
SignatureExtraction(cat = t(mut_mat_HCC),
                    outFilePath = paste0("extraction_signature_tools_lib/"),
                    nrepeats = 10,
                    nboots = 2,
                    nparallel = 2,
                    nsig = 2:6,
                    filterBestOfEachBootstrap = T,
                    filterBest_RTOL = 0.001,
                    mut_thr = 0,
                    type_of_extraction = "subs",
                    project = "HCC_v3",
                    parallel = TRUE,
                    nmfmethod = "brunet")
```

**Second question, how exactly do I choose the best number of signatures based on the output from function above?**

For example, I tried the exact function above for my dataset and get the plots attached (for HC, MC, and PAM). How would you select the best de novo extracted signature number based on the plots?

![Sigs_OverallMetrics_HCC_v4_nboots2_HC](https://user-images.githubusercontent.com/31801668/82109418-a8264d80-9703-11ea-996b-23c7a5644a14.jpg)
![Sigs_OverallMetrics_HCC_v4_nboots2_MC](https://user-images.githubusercontent.com/31801668/82109419-a8bee400-9703-11ea-9486-3c029f0ca399.jpg)
![Sigs_OverallMetrics_HCC_v4_nboots2_PAM](https://user-images.githubusercontent.com/31801668/82109420-a8bee400-9703-11ea-928d-3a3010d9f26e.jpg)

Thanks a lot!!!

Huan Wang

**Comment by Huan-Wang-S4** [comment]
Hi, Dear group

Over the weekend, I have also tried other parameters as below, basically `nrepeats` of 200 and `nboots` = 20 on the same dataset as above

```
SignatureExtraction(cat = t(mut_mat_HCC),
                    outFilePath = paste0("extraction_signature_tools_lib_bt_20_rp_200/"),
                    nrepeats = 200,
                    nboots = 20,
                    clusteringMethod = 'MC',
                    nparallel = 2,
                    nsig = 2:20,
                    filterBestOfEachBootstrap = T,
                    filterBest_RTOL = 0.001,
                    mut_thr = 0,
                    type_of_extraction = "subs",
                    project = "HCC_v3",
                    parallel = TRUE,
                    nmfmethod = "brunet")
```

And here are the plots. Would this help better in understanding how to choose the best signature number? 

![Sigs_OverallMetrics_HCC_v3_nboots20_HC](https://user-images.githubusercontent.com/31801668/82221957-a8cf0780-98ee-11ea-8c2d-f1cd8e52c348.jpg)
![Sigs_OverallMetrics_HCC_v3_nboots20_MC](https://user-images.githubusercontent.com/31801668/82221961-a9679e00-98ee-11ea-8d36-e055f1006bcc.jpg)
![Sigs_OverallMetrics_HCC_v3_nboots20_PAM](https://user-images.githubusercontent.com/31801668/82221962-aa003480-98ee-11ea-981b-88cfd84594e6.jpg)

I'd appreciate it deeply if you could provide some advice here

Thanks
Huan Wang

**Comment by andreadega** [comment]
Hi Huan Wang,

We do not recommend to use our tool for WES data, because we developed it and only used it on WGS data.

One issue is that bootstrapping on WES data can change the sample profile too much, because typically the average number of mutations in a WES sample is ~100x less than WGS. This also implies that one needs many more WES samples than WGS samples to have an accurate signature extraction.

You can try running the NMF r function directly on your original catalogue (https://cran.r-project.org/web/packages/NMF/vignettes/NMF-vignette.pdf) and see how it goes. If the results are encouraging then you can try to add some of our additional steps, like discarding runs with higher error (analogous to filter of best runs).
