### ISSUE TITLE
"object 'expected_chroms' not found"

### ISSUE THREAD

**Issue by slw287r** [Nik-Zainal-Group/signature.tools.lib#18]
Hi @andreadega,
I came into the unexpected `expected_chroms` when running `tabToIndelsClassification()` within the R package [doParallel](https://CRAN.R-project.org/package=doParallel). It seemed to be a typo in the parameter **expected_chrom** which should be `expected_chroms`:

https://github.com/Nik-Zainal-Group/signature.tools.lib/blob/5dcee5eb4fd9be2eba0586e4129ba53b3b00e056/R/tabToIndelsClassification.R#L44

Thanks, 
Richard

**Comment by andreadega** [comment]
Hi Richard,

Thanks for spotting that. I pushed a fix, hopefully it should be fine now.

This part of code is somewhat old and we hope to replace it in the near future with and improved classification and indels catalogues.

Cheers,
Andrea
