### ISSUE TITLE
variant caller for SNV, INDEL, CNV

### ISSUE THREAD

**Issue by Taekya** [Nik-Zainal-Group/signature.tools.lib#21]
Hello,

I'm trying to validate your methods; signature.tools.lib with PCAWG ovarian cancer samples.

I used variant caller dockstore-cgpwgs developed by your lab (Nik-Zainal-Group).
dockstore-cgp workflow includes caveman, cgppindel, brass, ascat-ngs for snv, indel, sv, cnv calling.

I used dockstore-cgp workflow outputs as inputs for signature.tools.lib.
I compare my scores above with your paper's supplementary tables 2 S8 sheet (A practical framework and online tool for mutational signature analyses show intertissue variation and driver dependencies), but the results was different as below.
(6/50 hrdetect score were mis-classified)

tumor ID | normal ID | my hrdtect scores | reference hrdetect score
c691d6b3-8e70-4951-8551-2ee4e4d0d10b | 22cff4a9-9e40-48a6-8e61-aaeae538bcf3 | 0.871910094 | 0.033352268
2f2eaecc-6509-423f-b63a-8c3bea1ba4a4 | 3867b293-9a47-44ad-bdbc-ca9d1448cb6f | 0.971619463 | 0.281175301
a1fc7064-abf5-477d-983e-576a784e1d40 | 8946ffc5-50df-4ec8-99a5-84c80176c8d0 | 0.984603157 | 0.033670814
745b8756-0eab-423f-8cde-e0ff1aaa6596 | 16ad07d7-9f33-405b-8f36-19ca1d5f6ec5 | 0.735746475 | 0.173750529
86f23897-dba0-4e89-8381-d174eaa6fcc1 | 2a79ee87-8c0f-4088-b925-5b5471ef57d8 | 0.802634363 | 0.555064522
6c31d730-1734-44ac-92b3-760981528723 | 27f94c73-e2e2-4420-a134-438e297f3cb3 | 0.82873389 | 0.542086759

I think that difference is due to variant calling methods.
so, how do you call variants (snv, indel, cnv, sv)? in your reads me documents specify structure variant caller was Manta and BRASS.
then, how about indel, cnv, snv caller?
If your calling methods werer same as me, how do you think about this problem?

Thank you ,
Taekya

**Comment by andreadega** [comment]
Hi Taekya,

Thanks for trying out our tools. Let me clarify that we did not develop dockstore-cgpwgs, but we do use it in some of our project. This docker image provides the wgs pipeline developed at the Sanger Institute in Cambridge, where we used to work but are no longer affiliated with.

This said, I should also clarify that we didn't use this pipeline to analyse the PCAWG data, but instead we used the consensus calls that the PCAWG groups have provided. In particular, several calling algorithms were used and a consensus set of mutations were provided for all mutation types. I suggest you start from these calls that should be available here https://dcc.icgc.org/releases/PCAWG/

I have also had a look at the samples you report and they do not look HR deficient, so I am inlined to think that our scores are ok. Did you use our HRDetect_pipeline function specifying to use the organ-specific signatures?
