### ISSUE TITLE
1kb size filter of SVs

### ISSUE THREAD

**Issue by annahoge** [Nik-Zainal-Group/signature.tools.lib#26]
Hello again!

For the rearrangement signatures shown at signal.mutationalsignatures.com, the smallest bin size is labeled "1kb to 10kb."  In signature.tools.lib's current state, the smallest bin size is labeled "1-10Kb."  I get different results running the tool with and without a (intrachromosomal) 1kb size filter applied to the input SV callset; it seems "1-10Kb" in this case means 1bp-10kb.

May I confirm that the rearrangement signatures shown at signal.mutationalsignatures.com were generated from SV callsets which excluded SVs < 1kb, and that signature.tools.lib does not automatically filter out SVs < 1kb?

Thank you so much!

Anna

**Comment by andreadega** [comment]
Hi Anna,

Yes indeed, this has been overlooked in the software package.

We assume that the user will apply his filters before using our package, and we also do so requiring minimum rearrangement size to be 1kb, so we didn't notice. To correct this, when generating the rearrangement catalogue we should also make sure that the bin 1-10Kb does not include rearrangement smaller than 1Kb.

Thank you for spotting this, I will add a fix in the next release.

Best Wishes,
Andrea

**Comment by annahoge** [comment]
Thank you so much for clarifying!  I appreciate it!

**Comment by andreadega** [comment]
Fixed in dev (not on github)
