### ISSUE TITLE
Signal Signature Networks

### ISSUE THREAD

**Issue by annahoge** [Nik-Zainal-Group/signature.tools.lib#27]
Hello!  Are the signature networks at https://signal.mutationalsignatures.com/explore/cancer/network still live?  The page is blank to me on the browsers I've tried.  Thank you so much!

**Comment by janczarn** [comment]
Hi. Apologies for this - the network was taken down temporarily in a website reorganisation, but will be available again soon. I'll reply when that is complete.

**Comment by janczarn** [comment]
The network is now back up. It is at a new URL, however: https://signal.mutationalsignatures.com/explore/study/1/network

**Comment by annahoge** [comment]
Thank you so much!
