### ISSUE TITLE
the chrTextColor and gridLineColor is swapped in the RCircos.Chromosome.Ideogram.Plot.my function

### ISSUE THREAD

**Issue by ipstone** [Nik-Zainal-Group/signature.tools.lib#28]
Thank you for the excellent circos plot functions! 

I noticed a small swap of coloring in the RCircos.Chromosome.Ideogram.Plot.my function:

https://github.com/Nik-Zainal-Group/signature.tools.lib/blob/ba836a3bc7a9ee516f16ccb7c4e92c60c16ac34f/R/RCircos_utils.R#L115

It seems in the function body, the usage of chrTextColor and gridLineColor got swapped. I was looking into some unintended coloring of my plots and noticed the swap.

**Comment by andreadega** [comment]
Thanks for reporting this. We will look into this and fix as appropriate.

**Comment by andreadega** [comment]
This is fixed as of v2.1.2
