### ISSUE TITLE
does not work with Windows?

### ISSUE THREAD

**Issue by ahwanpandey** [Nik-Zainal-Group/signature.tools.lib#29]
Hello,

Thanks for this tool!

I am trying to install this on windows but got this error:

![image](https://user-images.githubusercontent.com/8450532/131041763-525072ec-c2b8-4b55-8459-abfd4ce1f813.png)

seems the doMC package is not available for windows. Does this mean the "signature.tools.lib" is not compatible with windows?

Thanks,
Ahwan

**Comment by ahwanpandey** [comment]
I've been able to install the package by removing the "doMC" Import in the DESCRIPTION.

Also was able to run EXAMPLE1 all the way to HRDetect by commenting out the doMC code in HRDetect.R
`#doMC::registerDoMC(nparallel)`

So it does seem to run with a few tweaks, just not by default?

**Comment by andreadega** [comment]
Thanks for your bug report. I am currently away and back in September, but
I can guess that the problem may have to do with the fact that the doMC
function doesn't actually run things in parallel in Windows, so probably
some repositories do not make it available.

Once I am back I will check the code and see if doMC can be removed in
favour of other parallel frameworks that are compatible with Windows.

Andrea

**Comment by ahwanpandey** [comment]
Hi, thanks for your reply! I have managed to run most of the functions now without multithreading on a Windows machine after the above mentioned changes.

**Comment by ahwanpandey** [comment]
Same error with the `SignatureExtraction` function

 ```
extract_res = SignatureExtraction(
+   outFilePath = output_folder,
+   cat = category_counts_mat,
+   matrix_of_fixed_signatures = reference_signature_mat,
+   nboots = 20,
+   nrepeats = 200,
+   clusteringMethod = "MC",
+   nmfmethod = "brunet",
+   filterBest_RTOL=0.001
+ )
Loading required package: pkgmaker
Loading required package: registry
Loading required package: rngtools
Loading required package: cluster
NMF - BioConductor layer [OK] | Shared memory capabilities [NO: windows] | Cores 7/8
Error in loadNamespace(name) : there is no package called ‘doMC’
```

**Comment by ahwanpandey** [comment]
Seems `SignatureExtraction` is the slowest without parallelizing :(

**Comment by andreadega** [comment]
Our signature extraction framework, which includes selecting only the best
NMF runs, requires a lot of NMF runs (we suggest to set 20 bootstraps and
at least 100-200 repeats for each bootstrap for a given number of
signatures), so using it without parallelisation can be quite difficult for
a problem with hundreds of samples.

Currently we are working on a major new release of the signatures.tools.lib
package, which is quite some time away, so I will probably not upload the
fix soon. However I can suggest you what line of code to edit manually to
fix it, once I am back to work next week.

Thanks for your patience.
Andrea

**Comment by andreadega** [comment]
As a quick fix for Windows parallelisation, until the new release, please replace all instances of:

`doMC::registerDoMC(nparallel)`

with

`doParallel::registerDoParallel(nparallel)`

This code should be replaced in 4 files:

- R/matchedClustering.R
- R/signatures_utils.R
- R/SignatureExtractionLib.R
- R/HRDetect.R

**Comment by ahwanpandey** [comment]
Thanks @andreadega. Just tested and working for `SignatureFit_withBootstrap` and `SignatureExtraction`
