### ISSUE TITLE
R package versioning and tagging

### ISSUE THREAD

**Issue by pdiakumis** [Nik-Zainal-Group/signature.tools.lib#33]
Hi @andreadega,

I've noticed the R package has been updated several times with bug fixes/enhancements, but the version in the DESCRIPTION hasn't changed (`Version: 0.0.0.9000`) since the initial commit. Is it possible to bump the version (starting from e.g. `0.0.1`) when new important commits are added to the package? It helps a bit with reproducibility, or else we need to keep track of the commit hash.

In addition, you could also push a git tag (https://stackoverflow.com/a/18223354/2169986).
This will help when building the conda package (see #22) - my workaround is to clone your repo to my GitHub account and tag the latest version, but I think it would be much more appropriate for us to pull the tag directly from your account :-)

Thanks for the awesome tool!

**Comment by andreadega** [comment]
Thanks for the suggestion. Indeed we will introduce versioning and version tags in our upcoming 2.0 update. I hope we can release the new version soon, but it really depends on the anonymous reviewers right now :)

**Comment by andreadega** [comment]
We now have versioning and tagging.
