### ISSUE TITLE
Use with other reference genomes

### ISSUE THREAD

**Issue by gevro** [Nik-Zainal-Group/signature.tools.lib#38]
Hi,
If I already have a table of mutation counts for each trinucleotide context, from a different reference genome, is it possible to use this package?

In other words, all your current functions begin with VCF or chr/pos/ref/alt, but I already transformed that into trinucleotide contexts myself. Is there a way to skip the parts of your package that transform that into trinucleotide context counts, so that I can then use your package even though my mutations were called in a different reference genome?

Alternatively, are you able to specify the format of the SNV catalogue, and if I can put my variants manually into that format, will your tools still work even though they're from a different reference genome than what is supported?

Thanks.

**Comment by andreadega** [comment]
May I ask which function or script are you interested in using? Most of our high level functions and scripts support both vcf/tab inputs as well as the counts of mutation classes for each sample (we call them catalogues).

If you are using an R function, you can see the documentation typing ```?functionname```, while if you are using a command line script, you can type ```scriptname --help```.

**Comment by gevro** [comment]
I'm interested in SignatureExtraction and FitMS.

The question I guess, is if I want to make the mutation catalogue directly, what is the format of this? That way I can reformat my trinucleotide count data frame into your catalogue format?

**Comment by andreadega** [comment]
The format would be a ```matrix``` or ```data.frame```, with samples as columns and channels as rows. Column names should be set as the sample names and row names should be set as the channel names for the specific type of catalogue you are using. 

Admittedly we do not have a documentation page with the exact name of the channels at the moment. One place you can find them is in the body of the ```getTypeOfMutationsFromChannels``` function:

[link to getTypeOfMutationsFromChannels](https://github.com/Nik-Zainal-Group/signature.tools.lib/blob/bec86b5246ecbd808894be8acb19eb5725179593/R/signatureFitMultiStepLib.R#L713)

This function is only used internally so it is not currently available when loading the package via the ```library()``` function.

You can also find examples of catalogues in our ```tests``` folder.

**Comment by gevro** [comment]
Is it possible to change the tabToSNVcatalogue function so that any BSgenome name can be specified?

For, I have a custom: BSgenome.Hsapiens.T2T.CHM13v1, that I created.

Is the code for tabToSNVcatalogue general so that any BSgenome could be made to work?

**Comment by gevro** [comment]
Actually, no need to do the above for me (just a suggestion), since I can create the catalogue format manually myself. Thanks.

**Comment by andreadega** [comment]
No worries. To answer your question above about the ```tabToSNVcatalogue``` function, we currently do not allow for arbitrary genomes to be used, but rather only specific versions, for example by specifying ```hg19``` or ```hg38```. YOu can see the source code for details here:

[link to tabToSNVcatalogue](https://github.com/Nik-Zainal-Group/signature.tools.lib/blob/bec86b5246ecbd808894be8acb19eb5725179593/R/tabToSNVcatalogue.R#L14)
