### ISSUE TITLE
Signature 3 looks quite different on signal vs. cosmic signature 3?

### ISSUE THREAD

**Issue by ipstone** [Nik-Zainal-Group/signature.tools.lib#39]
Hello,

Congratulations on the new Science paper!

I am exploring SBS3 on Signal website: https://signal.mutationalsignatures.com/explore/referenceCancerSignature/62
But notice the profile looks different from the COSMIC signature 3 - https://cog.sanger.ac.uk/cosmic-signatures-production/documents/v3.2_SBS3_PROFILE.txt

For example, the highest frequency mutation on signal signature 3 is: T[C>G]T 0.066169308; which is almost twice the second highest: T[C>G]A 0.037053358

Whereas in cosmic signature 3: T[C>G]T	0.0235094037615046 - and the overall profile is flatter.

Is my observation correct? or perhaps I missed some important steps in understanding the SBS signatures in Signal (I assume SBS3 in Signal and Cosmic should be the same)? 

Thanks!

**Comment by andreadega** [comment]
Your observation is correct, there are some slight differences between the signatures we found and what is reported on the COSMIC website. Our analysis is completely independent from COSMIC, so this is normal, especially for a relatively featureless and flat signature like SBS3. What we report in Signal are our results, while at the same time in our Analyse tool on Signal we allow users to choose whether they want to use our signatures or the COSMIC signatures. We tend to refer to our version as 'reference signatures' or 'RefSig', so RefSig SBS3 as opposed to COSMIC SBS3.

It may also help to remember that our reference signature SBS3 and the COSMIC SBS3 are averages across different SBS3 signatures extracted from different organs or studies, and the way this aggregation is done may differ. In general, we advise to use the organ specific signatures when fitting, while we use the reference signatures to identify similar mutational processes across different organs.

**Comment by ipstone** [comment]
Thanks @andreadega for the clarification, very clear answers! 

I will close this issue.
