### ISSUE TITLE
problem with the SignatureExtraction function 

### ISSUE THREAD

**Issue by mishugeb** [Nik-Zainal-Group/signature.tools.lib#4]
I am using the signature.tools.lib in an R version 3.6.2 on an ubuntu image in AWS. 

When I am trying to run the following code:
**library(signature.tools.lib)
n_row <- 96
n_col <- 50
rnd_matrix <- round(matrix(runif(n_row*n_col,min = 0,max = 50),nrow = n_row,ncol = n_col))
colnames(rnd_matrix) <- paste0("C",1:n_col)
row.names(rnd_matrix) <- paste0("R",1:n_row)
SignatureExtraction(cat = rnd_matrix,
                    outFilePath = paste0("extraction_test_subs/"),
                    nrepeats = 10,
                    nboots = 2,
                    nparallel = 2,
                    nsig = 2:3,
                    mut_thr = 0,
                    type_of_extraction = "subs",
                    project = "test",
                    parallel = TRUE,
                    nmfmethod = "brunet")**

I am getting the following error:

**[STEP 1]: Reading and Preprocessing the Catalogue...Error in cat[nm, , drop = FALSE] : subscript out of bounds
Calls: SignatureExtraction -> sortCatalogue
Execution halted**

So do you know how can I successfully run the SignatureExtraction function?

Thanks

**Comment by andreadega** [comment]
Hi there,
The option type_of_extraction="subs" requires the row names (i.e. the channels) of the catalogues to have a specific format. You can find examples in the test folder.

If you want to run that random matrix you should set the type_of_extraction to "generic" (if I recall correctly just type ?SignatureExtraction to check the options)

**Comment by mishugeb** [comment]
Hi, 
Thanks for the help. Could you please tell how many repeats and bootstrap should use to get usable results from the SignatureExtraction? 
Also, is it possible to tell me from the following figure how many signatures should I select?
![image](https://user-images.githubusercontent.com/22875421/75314902-f1a68100-5815-11ea-9f90-f60076ec109f.png)

Many thanks

**Comment by andreadega** [comment]
Hi again,

I would advise you to run 20 bootstrap x 200 runs, and use 'MC' as clustering method. Once you do that, the optimal number of signatures may be clearer.

We have recently published a paper where you can find more information: https://www.nature.com/articles/s43018-020-0027-5

In particular Figure 1 and Suppl Figure 1 can help.

Andrea

**Comment by mishugeb** [comment]
Thanks for the suggestion. It works for smaller datasets. But when I am using datasets consist around 1000 samples, the jobs are running forever even with parallel processing with ~30 cores.

**Comment by andreadega** [comment]
Unfortunately, once one reaches 1000 samples the computing time required increases substantially. I reccommend one bootstrap per thread, as this is how it is parallelised currently (so for 20 bootstraps use 20 threads). From personal experience, it can take up to a week for 1000 samples.

**Comment by mishugeb** [comment]
Thanks again for the suggestion. So if I use a 28 core machine, is it ok if I use 100 bootstraps with x1 runs?

**Comment by andreadega** [comment]
If you see the supplementary figure 1 of our nature cancer paper, you will
see that you need at least 100 runs for each bootstrap, this is because our
method will select best runs within a RTOL of 0.001 among those 100 runs.
So the number of runs is more important than the number of bootstraps. Also
the more samples you have the more runs you should use. I understand it
will take some time, but I would still advise to run 20 bootstraps x
perhaps 200 runs.
Andrea

**Comment by mishugeb** [comment]
That makes sense. I will do that. Thanks again. I have one last question. I was looking for the activities/H matrix after running the extractions. Could you please tell me how to get the activity matrix after running the SignatureExtraction?

**Comment by andreadega** [comment]
We do not report the activity matrix from the extraction, only the
signatures. We then use a signature fit procedure (described in the paper)
to estimate the activities. We tend to think of the estimation of the
activities as a separate procedure, performed holding a given set of a
priori signatures fixed. This allows for more playing around with the
signature fit, for example excluding clear false positive signatures from
the fit.

**Comment by mishugeb** [comment]
Reasonable thinking! That makes sense.
