### ISSUE TITLE
FitMS: commonSignatures and rareSignatures parameters

### ISSUE THREAD

**Issue by gevro** [Nik-Zainal-Group/signature.tools.lib#41]
Hi,
1) What is the format for specifying commonSignatures and rareSignatures parameters in FitMS, if I do not want to use the 'organ' parameter?

I have samples from organs that are not in the signature.tools.lib catalogue, and I want to manually specify signatures.

2) Is there a way for rareSignatures to specify all possible signatures? Or is that too many signatures to try to fit against?

Thanks.

**Comment by andreadega** [comment]
1. The format shold be a data frame or matrix, with signature names as column names and channel names as row names.
2. rareSignatures can contatain as many signatures as you like, it might just take longer to check them all. Using default parameters of the FitMS function, only at most one of the rareSignatures will be allowed in the final fit. The output object will contain all rare signatures that are good candidates and you can check all the alternative solutions. There will be a selected solution, which is the one with the signature that gives the best fit. If you think that there is more than one rare signature, then you can increase the ```maxRareSigsPerSample```, though we do not recommend to increase it more than 2.

For more information see that fitMS manual in the ```userManuals``` folder.
