### ISSUE TITLE
SignatureExtraction: invalid 'times' argument

### ISSUE THREAD

**Issue by gevro** [Nik-Zainal-Group/signature.tools.lib#43]
Hi,
I'm getting this error:
SignatureExtraction(blah,outFilePath="~/Desktop/",nrepeats=200,nboots=20,nsig=2:5)

```
------------- START COMPUTATION ------------

[STEP 1]: Reading and Preprocessing the Catalogue...DONE
	> 8 Samples and 96 Mutations Correclty Processed

[STEP 2]: Finding Signatures
	> Running round 1

> Running for 2 Signatures (20 bootstraps)
.Error in rep(i, ns + ncol(matrix_of_fixed_signatures)) : 
  invalid 'times' argument
```

**Comment by andreadega** [comment]
Hi, I haven't seen this error before, thanks for reporting it.

Can I have more information about the parameters you specified? For example, it seems you specified ```matrix_of_fixed_signatures```, what are its dimensions?

**Comment by gevro** [comment]
Sorry I don't have that code and data set loaded anymore, so I can't recreate it. Will let you know if I see it again!

**Comment by andreadega** [comment]
Closed for inactivity and error could not be replicated
