### ISSUE TITLE
Rmarkdown Vignette for signature tools

### ISSUE THREAD

**Issue by nroak** [Nik-Zainal-Group/signature.tools.lib#44]
Thank you for putting together this incredible resource for the analysis of somatic mutational signatures. Is it possible to provide an R markdown vignette for the signatureEstimation pipeline or other plotting tools to describe standard plotting and QC steps in analyzing the mutational signatures? I understand if this is out of scope for this project, but would be an incredibly resource if you could provide one. Thank you once again.https://docs.github.com/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax

**Comment by andreadega** [comment]
Hi,

Thanks for the suggestion. In terms of documentation, we are providing examples in the README file, which you can run by going into the ```examples``` folder. Additionally, we have user manuals with more detailed explanation and examples in the ```userManuals``` folder.

**Comment by nroak** [comment]
The `userManuals` folder is what I was looking for, I missed it before. It may help to host these pdfs under the Wiki tab and link out on the Readme page. But again, just a small suggestion, feel free to ignore.
