### ISSUE TITLE
Signature file for environmental mutatagens

### ISSUE THREAD

**Issue by kw10** [Nik-Zainal-Group/signature.tools.lib#48]
Hello,

Do you have the mutation signature files for environmental signatures from this [page](https://signal.mutationalsignatures.com/explore/mutagens)?

I don't see them in the references signatures [folder](https://github.com/Nik-Zainal-Group/signature.tools.lib/tree/master/data/RefSigSBS_v2.03).

Thanks,
Kim

**Comment by andreadega** [comment]
Hi Kim,

Currently, the environmental signatures are not available within the ```signature.tools.lib``` github folders. It is a good suggestion, so I may add them in the future.

It should be possible to download each signature manually on Signal, there is currently no bulk download for all environmental signatures.

My advice is to click on the publication links on that page and download the signatures from each publication supplementary material files. See for example here: https://data.mendeley.com/datasets/m7r4msjb4c/3

**Comment by kw10** [comment]
Great, I'll try that.

Many thanks,
Kim
