### ISSUE TITLE
errors in genomeChartSV

### ISSUE THREAD

**Issue by tischfis** [Nik-Zainal-Group/signature.tools.lib#51]
two errors;

1)if bedpe file has chromosomes that don't start with "chr", code attempts to match character to non-character object
2) if sv_obj$junctions_catalogue is NULL, will throw an error

**Comment by andreadega** [comment]
Hi, sorry you had issues with the `genomeChartSV` function. This plot function is still a draft that will require an update in the future. In any case, I will try to provide a fix in the next days. What value did you use for the "genome.v" parameter? hg19 or hg38?

**Comment by tischfis** [comment]
hg19.  I was easily able to correct the bugs to get the plot function to work but wanted to bring to your attention for a stable release.  Happy to provide my fixes if you'd like.  Thanks.

**Comment by andreadega** [comment]
Thanks again for bringing this to our attention. We prefer to add our own fixes, so we make sure we don't introduce conflicts with current dev code, which is in a hidden repository. I will correct the code and hopefully add some other improvements with it if there is time.

**Comment by andreadega** [comment]
Hopefully this has been fixed now, if not let me know.
