### ISSUE TITLE
Conversion matrix to convert de novo signatures into reference signature exposures

### ISSUE THREAD

**Issue by jinmeshuo** [Nik-Zainal-Group/signature.tools.lib#52]
Thanks a lot for developing so great package! It helps me a lot. However, I'm running into a problem where I don't know how to get my own convert matrix. 

After I extracted de novo signatures, I concern that some signatures may be mixed signatures, thus I want to decompose the mixed signatures. I read your articles carefully in order to find the code for convert matrix which help me to map the de novo signatures to reference signatures as the articles said. I only found "008_fitOrganSigs_with_RefSigs.R" in your supplementary code, but it needs function "sigantureAssignmentLib.R“ which haven`t been supplied and I don’t know what format the input data are and how they are obtained. Can you teach me how to get convert matrix? Thank you very much.  

Shuoshuo

**Comment by andreadega** [comment]
Dear Shuoshuo,

I can't seem to find the version of the code you are referring to. Did you download it from Zenodo https://zenodo.org/record/5570307? The code in the `signatureAssignmentLib.R` file you mention is included in the `007_determineReferenceSignatures.R` file, and it is mostly just the function `fitSignaturesWithSignatures`.

**Comment by jinmeshuo** [comment]
> Dear Shuoshuo,
> 
> I can't seem to find the version of the code you are referring to. Did you download it from Zenodo https://zenodo.org/record/5570307? The code in the `signatureAssignmentLib.R` file you mention is included in the `007_determineReferenceSignatures.R` file, and it is mostly just the function `fitSignaturesWithSignatures`.

Yes, this is exactly what I want, thanks a lot! Thanks again for developing this useful package！

**Comment by andreadega** [comment]
Great!
