### ISSUE TITLE
Outdated function call when using devtools::test()

### ISSUE THREAD

**Issue by RPdavies** [Nik-Zainal-Group/signature.tools.lib#55]
Hi, the tests crash when executing `test-matchClustering.R`. Apparently the function `computeCorrelation()` does not exist. Is that true or is there something wrong with my installation? In addition, multiple other tests fail because `object 'cosmic30' not found`. Thanks for your time.

**Comment by andreadega** [comment]
That's odd, are you running `devtools::test()`, or are you running the code manually? Not all the code in the `tests` folder can be run manually. Can you try to run `devtools::test(pkg = ".",filter = "matchClustering")`, within the `signature.tools.lib` folder? Also can I make sure you have the latest code.

**Comment by RPdavies** [comment]
Thanks for your quick response @andreadega. I was indeed running devtools::test() when I got the errors. I was also running the latest version of the library, I installed it first time today. The good news is when I tried running the command again just now, it passes all the tests! On the other hand, I don't know what changed.. Thanks anyway!
