### ISSUE TITLE
bedpeToRearrCatalogue will crash if it filters out all variants

### ISSUE THREAD

**Issue by felixbeaudry** [Nik-Zainal-Group/signature.tools.lib#57]
Hi!

Great package! Just a little bug:

Somewhere around L87 of bedpeToRearrCatalogue, the list of SVs is filtered on size. If all variants do not pass this filter (eg. all SVs are < 1kb) the code crashes. 

https://github.com/Nik-Zainal-Group/signature.tools.lib/blob/master/R/bedpeToRearrCatalogue.R#L87

I'm sure this could be fixed with an extra if statement along the lines of `if (sum(toberemoved) != nrow(all_sv_annotated))`

**Comment by andreadega** [comment]
Thanks so much for reporting this. We have already fixed it in our dev branch and will be available in the next update.

**Comment by andreadega** [comment]
Should be fixed now in v2.4.4.
