### ISSUE TITLE
lung cancer samples mislabelled as cervical cancer in similar sample pie [https://signal.mutationalsignatures.com/]

### ISSUE THREAD

**Issue by selkamand** [Nik-Zainal-Group/signature.tools.lib#58]
Thanks for your work on these useful tools! 

I have a signature.tools.lib-adjacent bug to report so if this is the wrong place to log this,  do let me know where the ideal place to log this issue would be!

When using the 'Similar Samples' module from https://signal.mutationalsignatures.com/ I've noticed that lung cancers are actually labelled as 'cervix' in the 'similar samples' of the pie graph.

This bug can be reproduced by running the similar sample analysis on a known GEL lung cancer sample that's already in the signal database
[GEL-2344577-11_substitutions.csv](https://github.com/Nik-Zainal-Group/signature.tools.lib/files/13372586/GEL-2344577-11_substitutions.csv)

Signal appropriately identifies a sample with cosine similarity = 1 and it is labelled correctly as lung-cancer in the 'top 5 most similar samples section'
<img width="1018" alt="image" src="https://github.com/Nik-Zainal-Group/signature.tools.lib/assets/73202525/cc152136-b87c-4b0c-975e-19f3f3aeabe1">

But if you filter for similarity > 0.999 cosine similarity so you get just this sample in the pie-plot, you can see it gets labelled as 'cervix'

<img width="1015" alt="image" src="https://github.com/Nik-Zainal-Group/signature.tools.lib/assets/73202525/acd2edf1-64d3-44a8-9339-f8eabff3ba07">

**Comment by andreadega** [comment]
Thanks for reporting this. This is not an issue with the signature.tools.lib package, so I won't label it as a bug here. I have mention this issue to my colleagues and they will patch it soon. Next time, you can use [signal@mutationalsignatures.com](mailto:signal@mutationalsignatures.com) to send feedback to the Signal team directly.

**Comment by janczarn** [comment]
Thanks for letting us know about this issue @selkamand. We have diagnosed the issue and just need to deploy a fix. I will let you know when it's done.

**Comment by janczarn** [comment]
Just to let you know @selkamand, this bug has been fixed and deployed. You won't need to rerun the job to see the correct results.

Thanks for informing us!

**Comment by selkamand** [comment]
Thanks so much for the rapid fix!
