### ISSUE TITLE
vcfToIndelsClassfication() did not report classifications of insertions

### ISSUE THREAD

**Issue by ysuehara** [Nik-Zainal-Group/signature.tools.lib#7]
Hi
I tried `vcfToIndelsClassfication()` using a test file as follows.

`vcfToIndelsClassfication(indelsVCF.file = "~/signature.tools.lib/tests/testthat/test.indel.vcf.gz", sampleID = "test", genome.v = "hg19")`

Classifications of deletions worked well but those of insertions did not.
All of classifications for insertions showed "-".
Could you please let me know how to solve this problem?
Thanks for any help.

**Comment by andreadega** [comment]
Hi there,

What did you expect the output to be?

This function is meant to only classify deletions for now. We use it to
determine the proportion of deletions at microhomology and repeat regions.

**Comment by ysuehara** [comment]
Hi.
I've misunderstood that it could be used to classify not only deletions but also insertions.
Thank you for your reply.

**Comment by DarioS** [comment]
I thought it would be similar to [ID Signatures](https://cancer.sanger.ac.uk/cosmic/signatures/ID) because function name contains Indels.

**Comment by andreadega** [comment]
We will eventually support a more detailed indels classification in this software package.
