### ISSUE TITLE
Installation Process Downloads Many Large Annotations

### ISSUE THREAD

**Issue by DarioS** [Nik-Zainal-Group/signature.tools.lib#8]
There are four different annotation packages in the `Imports:` field of DESCRIPTION file. I think it would be better to move them into `Suggests:` and have code of the format:

```r
  if(!requireNamespace("BSgenome.Hsapiens.UCSC.hg38", quietly = TRUE))
    stop("The package 'BSgenome.Hsapiens.UCSC.hg38' could not be found. Please install it yourself.")
```

I think that most users would only need one of the genomes installed.

**Comment by andreadega** [comment]
Thanks for the suggestion, we will consider this in the future.

**Comment by andreadega** [comment]
Reference genomes BSgenome.Mmusculus.UCSC.mm10 and BSgenome.Cfamiliaris.UCSC.canFam3 are now moved to `Suggests:` in the DESCRIPTION file and need to be installed manually if required.
